services:
  calculator-node:
    build: ./nodejs
    container_name: calculator-node
    ports:
      - "3000:3000"

  calculator-java:
    build: ./java
    container_name: calculator-java
    ports:
      - "8080:3000"
    environment:
      - PORT=3000

  calculator-php:
    build: ./php
    container_name: calculator-php
    ports:
      - "9090:3000"

  calculator-c-asm:
    build: ./c-asm
    container_name: calculator-c-asm
    ports:
      - "3001:3001"
    environment:
      - PORT=3001